### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by m4sterbunny** [VCPR-ORG/publicAPI#19]
api/users/logins may have diff security to the others (if this is where token is accessed) -- comment from TW - how are DOS attacks handled on this endpoint?

**Comment by jehrlich** [comment]
The server efficiently checks for an API key in the request body, and returns a JSON error if a valid key is not found. It only does user lookup if the key is valid. Do you know of a better way at the API level? There can be DOS protection at higher levels, some of which may be in place by default, but I have not investigated.
It might be better not to respond to requests with no valid API key, a change which would not be difficult.

**Comment by m4sterbunny** [comment]
So, it was only the login endpoint that made me wonder, where there is (and can't be) security: 
paths:
  /api/users/logins:
    post:
      operationId: userLogin
      tags:
        - editor
        - idempotent
      security: []
      summary: user login
I actually have never asked Devs how they control against DOS, many customers of mine do throttle requests as and when they want to, was just a thought, but way outside my knowledge zone to assist with.
